{
 "title": "sr",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ResponseTime 95% tile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_response_time_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Avg 24h - response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_response_time_seconds_sum[24h])) / sum(rate(vertx_http_server_response_time_seconds_count[24h]))"
    }
   ]
  },
  {
   "title": "response_time_seconds_max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "vertx_http_server_response_time_seconds_max"
    }
   ]
  },
  {
   "title": "response_time_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "vertx_http_server_response_time_seconds_count"
    }
   ]
  },
  {
   "title": "rate_response_time_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(vertx_http_server_response_time_seconds_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "vertx_http_server_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "vertx_http_server_requests_total"
    }
   ]
  },
  {
   "title": "vertx_http_server_active_connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "vertx_http_server_active_connections"
    }
   ]
  }
 ]
}