---
version: "2"
services:
  hbase:
    build: .
    image: hbase
    hostname: hbase
    container_name: hbase
    volumes:
      - /data/hbase:/tmp
    command: >
      bash -c "bin/start-hbase.sh"
    expose:
      - "16010"
      - "2181"
    networks:
      sr_cluster_network:
        ipv4_address: ${HBASE_IP}

networks:
  sr_cluster_network:
    external: true
