version: '2'

services:
  fluentd:
    build: .
    container_name: fluentd
    volumes:
      - /data/fluentd:/fluentd/log
      - ./fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      sr_cluster_network:
        ipv4_address: ${FLUENTD_IP}

networks:
  sr_cluster_network:
    external: true
