---
  version: '2'
  services:
  
    superset:
      build: .
      container_name: superset
      volumes:
        - /data/superset:/var/lib/superset
      ports:
        - "8088:8088"
      networks:
        sr_cluster_network:
          ipv4_address: ${SUPERSET_IP}

  networks:
    sr_cluster_network:
      external: true