version: '2'

services:
  zipkin:
    image: 'openzipkin/zipkin'
    container_name: zipkin
    ports:
      - "9000:9411"
      - "9410:9410"
    networks:
      sr_cluster_network:
        ipv4_address: ${ZIPKIN_IP}

networks:
  sr_cluster_network:
    external: true