{
 "title": "SR",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Respone Time Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(vertx_pool_queue_time_seconds_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(vertx_http_server_response_time_seconds_sum[5m])/ rate(vertx_http_server_response_time_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "vertx_http_server_active_connections"
    }
   ]
  },
  {
   "title": "Request Bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(vertx_http_server_request_bytes_count[$__rate_interval])"
    }
   ]
  }
 ]
}