version: "2.2"

services:
  kafka_zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: kafka_zookeeper
    hostname: kafka_zookeeper
    expose:
      - "2181"
      - "2888"
      - "3888"
    volumes:
      - sr_zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      sr_cluster_network:
        ipv4_address: ${ZOOKEEPER_IP}

  kafka:
    image: docker.io/bitnami/kafka:3.1
    container_name: kafka
    hostname: kafka
    expose:
      - "9092"
    volumes:
      - sr_kafka_data:/bitnami
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_IP}:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=kafka_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      sr_cluster_network:
        ipv4_address: ${KAFKA_IP}
    depends_on:
      - kafka_zookeeper

volumes:
  sr_zookeeper_data:
    external: true
  sr_kafka_data:
    external: true

networks:
  sr_cluster_network:
    external: true