version: "2.2"

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    hostname: cassandra
    expose:
      - "7000"
      - "9042"
    volumes:
      - /data/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_LISTEN_ADDRESS=${CASSANDRA_IP}
      - CASSANDRA_BROADCAST_ADDRESS=${CASSANDRA_IP}
    networks:
      sr_cluster_network:
        ipv4_address: ${CASSANDRA_IP}

networks:
  sr_cluster_network:
    external: true