version: '2'

services:
  prometheus:
    image: 'prom/prometheus'
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/prometheus:/prometheus
    ports:
      - "9090:9090"
    networks:
      sr_cluster_network:
        ipv4_address: ${PROMETHEUS_IP}

networks:
  sr_cluster_network:
    external: true